config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # # get /user/5  | get /users/banana
  # post '/users', create
  # patch '/users/:id', update
  # delete '/users/:id', destroy
  resources :users
  # resources :users, only: [:index, :create, :update, :destroy, :show]
  # resources :users, except: [:edit, :new]
  resource :session, only: [:new, :create, :destroy]
  resources :chirps
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chirp.rb
class Chirp < ApplicationRecord
    belongs_to :user
        foreign_key: :user_id,
        class_name: :User
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, :password_digest, presence: true
    validates :username, :session_token, presence: true, uniqueness: true
    validates :password, length: { minimum: 6 },allow_nil: true

    attr_reader :password
    # attr_reader is used in the validation of the password
    
    after_initialize :ensure_session_token
    # before_validation :ensure_session_token
    # set the session_token using the ensure_session_token method

    has_many :chirps
        foreign_key: :user_id,
        class_name: :Chirp

    # S - self.find_by_credentials
    # P - password=
    # I - is_password?
    # R - reset_session_token!
    # E - ensure_session_token

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        # find the user by their username
        user && user.is_password?(password) ? user : nil
        # return nil is the find_by method returns nil
        # use the User#is_password? method to compare the password give with the password_digest from the DB
        # return the user is they match or return nil
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        # create the hashed/salted password_digest from the given password using BCrypt
        @password = password
        # set an instance variable for use in the validation
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
        # create a new instance of the BCrypt::Password class with the password_digest for this instance
        # then call the BCrypt::Password#is_password? method to compare the given password
        # (this method does not use any recursion)
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        # set the session token to a new random string
        self.save!
        # .save! throws and errow and stops code execution= => easier to debug
        self.session_token
        # return the value of the session token for use later
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
        # makes sure the user has a session_token when first created
        # the ||= is important later for logging in!
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    # C - current_user
    # R - require_logged_in
    # L - login
    # L - logout
    # L - logged_in?

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end

    def logged_in?
        !!current_user
    end

    def logout
        if logged_in?
            current_user.reset_session_token!
            @current_user = nil
            session_token[:session_token] = nil
        end
    end

end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
    before_action :require_logged_in, only: [:edit, :update]

    def edit
        @chirp = Chirp.find_by(id: params[:id])
        render :edit
    end

    def update
        @chirp = Chirp.find_by(id: params[:id])
        # @chirp = current_user.chirps.find_by(id: params[:id])

        # if @chirp && @chirp.update(chirp_params)
        if @chirp.user_id == current_user.id && @chirp.update(chirp_params)
            redirect_to user_url(@chirp.user_id)
        else
            flash.now[:errors] = ["You can't do that silly"]
            render :edit
        end
    end

    private 
    def chirp_params
        params.require(:chirp).permit(:body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action(:require_logged_in, {only: :destroy})
    
    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user
            login(@user)
            redirect_to users_url
        else
            flash.now[:errors] = ["Invalid credentials"]
            render :new
        end
    end

    def destroy
        logout
        redirect_to new_session_url
    end

    # Let's not do this

    # private
    # def session_params
    #     params.require(:user).permit(:username, :password)
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :require_logged_in, only: [:index, :show, :edit, :update, :destroy]
    before_action :require_logged_in, except: [:new, :create]

    def index
        # debugger
        # params[:id]???? => answer: nope
        users = User.all
        render json: users
    end

    def new
        @user = User.new
        render :new
    end

    def edit
        @user = User.find_by(id: params[:id])
        render :edit
    end

    def show
        # debugger
        user = User.find_by(id: params[:id])
        render json: user
    end

    def create
        user = User.new(user_params)
        if user.save
            render json: user
        else
            render json: user.errors.full_messages, status: 422
        end
    end

    def update
        user = User.find_by(id: params[:id])
        if user.update(user_params)
            # render json: user
            redirect_to user_url(user)
        else
            render json: user.errors.full_messages, status: 422
        end
    end
    
    def destroy
        user = User.find_by(id: params[:id])
        if user.destroy
            render json: "Bye bye user"
        else
            render json: "Unsuccessful"
        end
    end

    private
     def user_params
        params.require(:user).permit(:username, :age, :email, :is_cool?)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chirps/edit.html.erb
<!-- <form action=<%#= chirp_url(@chirp) %> method="post"> -->
<form action=<%= chirp_url(params[:id]) %> method="post">
    <input type="hidden" name="_method" value="PATCH">
    <label>Body:
        <input type="text" name="chirp[body]" value=<%= @chirp.body %>>
    </label>
    <input type="submit" value="Edit Chirp">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFlexApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if logged_in? %>
      <h1>Hello <%= current_user.username %></h1>
    <%= end %>
    <%= flash[:errors]  %>
  </body>
</html>

app/views/users/edit.html.erb
<form action=<%= user_url(@user) %> method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <label>Username:
        <input type="text" name="user[username]" value=<%= @user.username %>>
    </label>
    <label>Email:
        <input type="text" name="user[email]" value=<%= @user.email %>>
    </label>
    <label>Age:
        <input type="text" name="user[age]" value=<%= @user.age %>>
    </label>
    <input type="submit" value="Update User">
</form>

app/views/users/new.html.erb
<form action=<%= users_url %> method="POST">
    <label>Username:
        <input type="text" name="user[username]" value=<%= @user.username %>>
    </label>
    <label for="email">Email:</label>
    <input id="email" type="text" name="user[email]" value=<%= @user.email %>>
    <label>Age:
        <input type="text" name="user[age]" value=<%= @user.age %>>
    </label>
    <input type="submit" value="Create User">
</form>